name: PHP CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run PHPUnit with coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}